In [1]:
import pandas as pd
data=pd.read_csv("minst-train.csv")
data

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
12085      1       0       0       0       0       0       0       0       0   
12086      0       0       0       0       0       0       0       0       0   
12087      6       0       0       0       0       0       0       0       0   
12088      0       0       0       0       0       0       0       0       0   
12089      5       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...       0.0       0.0       0.0       0.0       0.0   
1           0  ...       0.0       0.0       0.0       0.0       0.0   
2           0  ...       0.0       0.0       0.0       0.0       0.0   
3           0  ...       0.0       0.0       0.0       0.0       0.0   
4           0  ...       0.0       0.0       0.0       0.0       0.0   
...       ...  ...       ...       ...       ...       ...       ...   
12085       0  ...       0.0       0.0       0.0       0.0       0.0   
12086       0  ...       0.0       0.0       0.0       0.0       0.0   
12087       0  ...       0.0       0.0       0.0       0.0       0.0   
12088       0  ...       0.0       0.0       0.0       0.0       0.0   
12089       0  ...       NaN       NaN       NaN       NaN       NaN   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0           0.0       0.0       0.0       0.0       0.0  
1           0.0       0.0       0.0       0.0       0.0  
2           0.0       0.0       0.0       0.0       0.0  
3           0.0       0.0       0.0       0.0       0.0  
4           0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
12085       0.0       0.0       0.0       0.0       0.0  
12086       0.0       0.0       0.0       0.0       0.0  
12087       0.0       0.0       0.0       0.0       0.0  
12088       0.0       0.0       0.0       0.0       0.0  
12089       NaN       NaN       NaN       NaN       NaN  

[12090 rows x 785 columns]

In [4]:
features=data.columns[1:]

X=data[features]
y=data['label']

In [5]:
X

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
12085       0       0       0       0       0       0       0       0       0   
12086       0       0       0       0       0       0       0       0       0   
12087       0       0       0       0       0       0       0       0       0   
12088       0       0       0       0       0       0       0       0       0   
12089       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...       0.0       0.0       0.0       0.0       0.0   
1           0  ...       0.0       0.0       0.0       0.0       0.0   
2           0  ...       0.0       0.0       0.0       0.0       0.0   
3           0  ...       0.0       0.0       0.0       0.0       0.0   
4           0  ...       0.0       0.0       0.0       0.0       0.0   
...       ...  ...       ...       ...       ...       ...       ...   
12085       0  ...       0.0       0.0       0.0       0.0       0.0   
12086       0  ...       0.0       0.0       0.0       0.0       0.0   
12087       0  ...       0.0       0.0       0.0       0.0       0.0   
12088       0  ...       0.0       0.0       0.0       0.0       0.0   
12089       0  ...       NaN       NaN       NaN       NaN       NaN   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0           0.0       0.0       0.0       0.0       0.0  
1           0.0       0.0       0.0       0.0       0.0  
2           0.0       0.0       0.0       0.0       0.0  
3           0.0       0.0       0.0       0.0       0.0  
4           0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
12085       0.0       0.0       0.0       0.0       0.0  
12086       0.0       0.0       0.0       0.0       0.0  
12087       0.0       0.0       0.0       0.0       0.0  
12088       0.0       0.0       0.0       0.0       0.0  
12089       NaN       NaN       NaN       NaN       NaN  

[12090 rows x 784 columns]

In [6]:
y

0        1
1        0
2        1
3        4
4        0
        ..
12085    1
12086    0
12087    6
12088    0
12089    5
Name: label, Length: 12090, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X/255,y,test_size=0.15,random_state=0)

In [9]:
import numpy as np
from keras.utils import np_utils

print(np.unique(y_train,return_counts=True))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64), array([1003, 1143, 1068, 1037, 1001,  937, 1034, 1063,  982, 1008],
      dtype=int64))


In [10]:
n_classes=10
y_train=np_utils.to_categorical(y_train,n_classes)

In [11]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [12]:
y_test=np_utils.to_categorical(y_test,n_classes)

In [15]:
from keras.models import Sequential
from keras.layers import Dense,Dropout

mnist_nn=Sequential()

In [14]:
#hidden layer
mnist_nn.add(Dense(units=100,kernel_initializer='uniform',activation='relu',input_shape=(784,)))

#output layer
mnist_nn.add(Dense(units=10,kernel_initializer='uniform',activation='softmax'))

mnist_nn.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

mnist_nn.fit(X_train,y_train,batch_size=64,epochs=20,validation_data=(X_test,y_test))


Epoch 1/20
161/161 [==============================] - 2s 7ms/step - loss: 0.8415 - accuracy: 0.8039 - val_loss: nan - val_accuracy: 0.8886
Epoch 2/20
161/161 [==============================] - 1s 5ms/step - loss: 0.3284 - accuracy: 0.9079 - val_loss: nan - val_accuracy: 0.9052
Epoch 3/20
161/161 [==============================] - 1s 5ms/step - loss: 0.2624 - accuracy: 0.9251 - val_loss: nan - val_accuracy: 0.9101
Epoch 4/20
161/161 [==============================] - 1s 5ms/step - loss: 0.2248 - accuracy: 0.9335 - val_loss: nan - val_accuracy: 0.9201
Epoch 5/20
161/161 [==============================] - 1s 5ms/step - loss: 0.1900 - accuracy: 0.9466 - val_loss: nan - val_accuracy: 0.9272
Epoch 6/20
161/161 [==============================] - 1s 5ms/step - loss: 0.1679 - accuracy: 0.9520 - val_loss: nan - val_accuracy: 0.9333
Epoch 7/20
161/161 [==============================] - 1s 6ms/step - loss: 0.1418 - accuracy: 0.9597 - val_loss: nan - val_accuracy: 0.9272
Epoch 8/20
161/161 [=======

In [16]:
#hidden layer
mnist_nn.add(Dense(units=100,kernel_initializer='uniform',activation='relu',input_shape=(784,)))

mnist_nn.add(Dropout(0.2))

#output layer
mnist_nn.add(Dense(units=10,kernel_initializer='uniform',activation='softmax'))

mnist_nn.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

mnist_nn.fit(X_train,y_train,batch_size=64,epochs=20,validation_data=(X_test,y_test))


Epoch 1/20
161/161 [==============================] - 2s 7ms/step - loss: 0.9254 - accuracy: 0.7653 - val_loss: nan - val_accuracy: 0.8881
Epoch 2/20
161/161 [==============================] - 1s 6ms/step - loss: 0.3821 - accuracy: 0.8902 - val_loss: nan - val_accuracy: 0.9008
Epoch 3/20
161/161 [==============================] - 1s 6ms/step - loss: 0.3034 - accuracy: 0.9131 - val_loss: nan - val_accuracy: 0.9079
Epoch 4/20
161/161 [==============================] - 1s 5ms/step - loss: 0.2611 - accuracy: 0.9251 - val_loss: nan - val_accuracy: 0.9190
Epoch 5/20
161/161 [==============================] - 1s 5ms/step - loss: 0.2260 - accuracy: 0.9351 - val_loss: nan - val_accuracy: 0.9223
Epoch 6/20
161/161 [==============================] - 1s 5ms/step - loss: 0.1986 - accuracy: 0.9417 - val_loss: nan - val_accuracy: 0.9305
Epoch 7/20
161/161 [==============================] - 1s 5ms/step - loss: 0.1791 - accuracy: 0.9452 - val_loss: nan - val_accuracy: 0.9366
Epoch 8/20
161/161 [=======

In [18]:
y_pred=mnist_nn.predict(X_test)
y_pred

57/57 [==============================] - 0s 2ms/step


array([[1.61854780e-10, 6.81517918e-08, 9.69613367e-09, ...,
        5.47840836e-15, 3.53387506e-08, 2.26484711e-13],
       [8.51700044e-09, 3.43160150e-06, 9.89751160e-01, ...,
        6.42157113e-03, 7.81774077e-07, 3.96075023e-07],
       [4.87626494e-06, 2.82818190e-04, 1.76925296e-05, ...,
        9.93171692e-01, 8.99986990e-05, 5.34437876e-03],
       ...,
       [1.35765631e-05, 5.58334989e-07, 3.85838561e-02, ...,
        5.44331698e-11, 1.22379504e-06, 1.17898850e-11],
       [7.75964797e-01, 5.24189963e-04, 2.18669680e-04, ...,
        6.13851473e-04, 3.09554780e-05, 2.02946990e-06],
       [1.48836725e-05, 9.11768153e-03, 9.58105738e-05, ...,
        8.30539793e-05, 9.31161642e-01, 4.00990574e-03]], dtype=float32)

In [19]:
y_pred=(y_pred >0.9)
y_pred

array([[False, False, False, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [False, False, False, ...,  True, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False]])